# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(620, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(620, 520))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_result = QtWidgets.QTableWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_result.sizePolicy().hasHeightForWidth())
        self.tableWidget_result.setSizePolicy(sizePolicy)
        self.tableWidget_result.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableWidget_result.setAutoFillBackground(False)
        self.tableWidget_result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_result.setLineWidth(1)
        self.tableWidget_result.setMidLineWidth(1)
        self.tableWidget_result.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_result.setAutoScroll(True)
        self.tableWidget_result.setAlternatingRowColors(True)
        self.tableWidget_result.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_result.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_result.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_result.setRowCount(5)
        self.tableWidget_result.setColumnCount(2)
        self.tableWidget_result.setObjectName("tableWidget_result")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setHorizontalHeaderItem(1, item)
        self.tableWidget_result.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_result.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_result.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_result)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_notes = QtWidgets.QLabel(self.centralWidget)
        self.label_notes.setMinimumSize(QtCore.QSize(200, 25))
        self.label_notes.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(10)
        self.label_notes.setFont(font)
        self.label_notes.setAutoFillBackground(False)
        self.label_notes.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_notes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_notes.setText("")
        self.label_notes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_notes.setWordWrap(True)
        self.label_notes.setObjectName("label_notes")
        self.horizontalLayout_2.addWidget(self.label_notes)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.Label_target = QtWidgets.QLabel(self.centralWidget)
        self.Label_target.setObjectName("Label_target")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_target)
        self.LineEdit_target = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit_target.setMinimumSize(QtCore.QSize(200, 25))
        self.LineEdit_target.setStatusTip("")
        self.LineEdit_target.setObjectName("LineEdit_target")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_target)
        self.Label_user = QtWidgets.QLabel(self.centralWidget)
        self.Label_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_user.setObjectName("Label_user")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_user)
        self.LineEdit_user = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit_user.setMinimumSize(QtCore.QSize(200, 25))
        self.LineEdit_user.setObjectName("LineEdit_user")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_user)
        self.Label_pwd = QtWidgets.QLabel(self.centralWidget)
        self.Label_pwd.setObjectName("Label_pwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_pwd)
        self.LineEdit_pwd = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit_pwd.setMinimumSize(QtCore.QSize(200, 25))
        self.LineEdit_pwd.setText("")
        self.LineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LineEdit_pwd.setObjectName("LineEdit_pwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_pwd)
        self.gapLabel = QtWidgets.QLabel(self.centralWidget)
        self.gapLabel.setObjectName("gapLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gapLabel)
        self.LineEdit_timegap = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit_timegap.setMinimumSize(QtCore.QSize(200, 25))
        self.LineEdit_timegap.setObjectName("LineEdit_timegap")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_timegap)
        self.horizontalLayout.addLayout(self.formLayout)
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStatusTip("")
        self.checkBox.setAutoFillBackground(True)
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_head = QtWidgets.QLabel(self.centralWidget)
        self.label_head.setMinimumSize(QtCore.QSize(0, 120))
        self.label_head.setObjectName("label_head")
        self.gridLayout.addWidget(self.label_head, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        self.pushButton_start.clicked.connect(self.Start_Run)
        self.pushButton_stop.clicked.connect(self.Stop_Run)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微信公众号文章"))
        self.tableWidget_result.setSortingEnabled(False)
        item = self.tableWidget_result.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_result.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "URL"))
        self.Label_target.setText(_translate("MainWindow", "目标公众号英文名"))
        self.LineEdit_target.setPlaceholderText(_translate("MainWindow", "为空则默认新华社(xinhuashefabu1)"))
        self.Label_user.setText(_translate("MainWindow", "个人公众号账号"))
        self.LineEdit_user.setPlaceholderText(_translate("MainWindow", "为空则自动打开页面后手动输入"))
        self.Label_pwd.setText(_translate("MainWindow", "个人公众号密码"))
        self.LineEdit_pwd.setPlaceholderText(_translate("MainWindow", "为空则自动打开页面后手动输入"))
        self.gapLabel.setText(_translate("MainWindow", "查询间隔(s)"))
        self.LineEdit_timegap.setPlaceholderText(_translate("MainWindow", "为空则默认为10s,一页约10条，越短越快被限制"))
        self.checkBox.setWhatsThis(_translate("MainWindow", "记住密码"))
        self.pushButton_start.setText(_translate("MainWindow", "启动(*^▽^*)"))
        self.pushButton_stop.setText(_translate("MainWindow", "终止￣へ￣"))
        self.label_head.setText(_translate("MainWindow", "****************************************************************************************************\n"
"* 程序原理:\n"
">> 通过selenium登录获取token和cookie，再自动爬取和下载\n"
"* 使用前提： *\n"
">> 电脑已装Firefox、Chrome、Opera、Edge等浏览器\n"
">> 下载selenium驱动放入python安装目录，将目录添加至环境变量(https://www.seleniumhq.org/download/)\n"
">> 申请一个微信公众号(https://mp.weixin.qq.com)\n"
"                         Copyright © SXF  本软件禁止一切形式的商业活动\n"
"****************************************************************************************************"))


